logo: 'images/aroga-logo.png'
subscribe:
  subtitle: Our Newsletter
  heading: Sign Up to Our Newsletter
  action: Sign Up

footer:
  social:
    - icon: icon-facebook
      link: https://facebook.com
    - icon: icon-linked-in
      link: https://linkedin.com
    - icon: icon-Instagram
      link: https://instagram.com
  menus:
    - title: Categories
      list:
        - title: Features
          link: /featured
        - title: Best Selling
          link: /best-selling
        - title: Quality Scale
          link: /quality-scale
    - title: Legal
      list:
        - title: Terms of Service
          link: /terms
        - title: Privacy Policy
          link: /privacy-policy
        - title: Laboratory Test
          link: /laboratory-test
    - title: Company
      list:
        - title: About
          link: /about
        - title: Team
          link: /team
        - title: Contact
          link: /contact